CLOSE: str = '4. close'

MACD: str = 'MACD'
MACD_MIN: str = 'MIN'
MACD_MAX: str = 'MAX'
MACD_SIGNAL: str = 'SIG'
REGRESSION_RANGE: str = 'REGRESSION_RANGE'

BEARISH: str = 'BEARISH'
BULLISH: str = 'BULLISH'
CROSSOVER: str = 'CROSSOVER'

SOARING: str = 'SOARING'
DIVERGING: str = 'DIVERGING'
RANGING: str = 'RANGING'
CONVERGING: str = 'CONVERGING'
PLUMMETING: str = 'PLUMMETING'

RSI: str = 'RSI'
PERIODS: str = 'PERIODS'
PREVIOUS_AVERAGE_GAIN: str = 'PREVIOUS_AVERAGES'
PREVIOUS_AVERAGE_LOSS: str = 'PREVIOUS_LOSS'