HIGH: str = '2. high'
LOW: str = '3. low'
CLOSE: str = '4. close'
VOLUME: str = '5. volume'

SPAN: str = 'SPAN'

MACD: str = 'MACD'
MIN: str = 'MIN'
MAX: str = 'MAX'
SIGNAL: str = 'SIGNAL'
POSITION: str = 'POSISTION'

BEARISH: str = 'BEARISH'
BULLISH: str = 'BULLISH'
CROSSOVER: str = 'CROSSOVER'

SOARING: str = 'SOARING'
DIVERGING: str = 'DIVERGING'
RANGING: str = 'RANGING'
CONVERGING: str = 'CONVERGING'
PLUMMETING: str = 'PLUMMETING'

RSI: str = 'RSI'
RS: str = 'RS'
# CHANGES: str = 'CHANGES'
AVG_LOSS: str = 'AVG_LOSS'
AVG_GAIN: str = 'AVG_GAIN'
PERIODS: str = 'PERIODS'
PREV_AVG_GAIN: str = 'PREV_AVG_GAIN'
PREV_AVG_LOSS: str = 'PREV_AVG_LOSS'

OBV: str = 'OBV'
MULTIPLIER: str ='MULTIPLIER'
POSITIVE: str = 'POSITIVE'
NEGATIVE: str = 'NEGATIVE'

ADX: str = 'ADX'
DX: str = 'DX'
POS_DI: str = 'POS_DI'
NEG_DI: str = 'NEG_DI'
POS_DM_AVG: str = 'POS_DM_AVG'
NEG_DM_AVG: str = 'NEG_DM_AVG'
TR_AVG: str = 'TR_AVG'
POS_DM: str = 'POS_DM'
NEG_DM: str = 'NEG_DM'
TR: str = 'TR'
