SYMBOL: str = 'SYMBOL'
COFING_SPREAD_SHEET_ID: str = 'COFING_SPREAD_SHEET_ID'

ALPHA_VANTAGE_ID: str = 'ALPHA_VANTAGE_ID'
WEB_HOOK_URL: str = 'WEB_HOOK_URL'

FB_API_KEY: str = ''
FB_AUTH_DOMAIN: str = ''
FB_DB_URL: str = ''
FB_STORAGE_BUCKET: str = ''
FB_SERVICE_ACCOUNT: str = ''