# Firebase DB key
TICKER: str = 'TICKER'
TIMEZONE: str = 'TIMEZONE'
INTERVAL: str = 'INTERVAL'
OPENING_HOURS: str = 'OPENING_HOURS'
CLOSING_HOURS: str = 'CLOSING_HOURS'
SHOULD_TRADE: str = 'SHOULD_TRADE'